apiVersion: apps/v1
kind: Deployment
metadata:
  name: mantis-app-deployment
  labels:
    app: mantis-app
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: mantis-app
  template:
    metadata:
      labels:
        app: mantis-app
    spec:
      containers:
      - name: web-app
        image: pratiksanas5/nodejs-app:v1
        ports:
        - containerPort: 3000