apiVersion: apps/v1
kind: Deployment
metadata:
  name: mantis-app-deployment
  namespace: production
  labels:
    app: mantis-app
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: mantis-app
  template:
    metadata:
      labels:
        app: mantis-app
    spec:
      containers:
      - name: web-app
        image: gcr.io/bionic-axon-368601/mantis-app:v1
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
 name: mantisappsvc
 namespace: production
 labels:
   app: mantis-app
spec:
 type: LoadBalancer
 selector:
   app: mantis-app
 ports:
 - port: 3001
   targetPort: 3000
